sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

addons:
    apt:
      packages:
        - mingw-w64

script:
  # MinGW 32bit build.
  - mkdir ${TRAVIS_BUILD_DIR}/build_mingw32
  - cd ${TRAVIS_BUILD_DIR}/build_mingw32
  - make KBUILD_SRC=${TRAVIS_BUILD_DIR}/src -f ../src/Makefile -j 4 mingw32_defconfig
  - make -j 4
  # MinGW 64bit build.
  - mkdir ${TRAVIS_BUILD_DIR}/build_mingw64
  - cd ${TRAVIS_BUILD_DIR}/build_mingw64
  - make KBUILD_SRC=${TRAVIS_BUILD_DIR}/src -f ../src/Makefile -j 4 mingw64_defconfig
  - make -j 4
