sudo: false

language: cpp

compiler:
  - gcc

addons:
    apt:
      packages:
        - binutils-mingw-w64
        - gcc-mingw-w64
        - g++-mingw-w64
        - mingw-w64-dev

script:
  - cd ./src
  - make -j4 mingw32_defconfig
  - make -j4
