sudo: false

language: cpp

compiler:
  - gcc

addons:
    apt:
      packages:
        - binutils-mingw-w64
        - gcc-mingw-w64
        - g++-mingw-w64

script:
  - cd ./src
  - make mingw32_defconfig
  - make
