sudo: required
dist: trusty

language: cpp
compiler:
- gcc

addons:
  apt:
    packages:
    - binutils-mingw-w64
    - gcc-mingw-w64
    - g++-mingw-w64
    - wine
    - wine:i386

script:
- ./build.sh
- wine busybox-win32.exe
- wine64 busybox-win64.exe

deploy:
  provider: releases
  api_key:
    secure: Bw7cjF4JMkbtr0VV+BZTv0/ryNdHeTloWbrCRef8mqTrbPSX5G6Jg4pLfUb1hBUymMCvHRyaUft5jU6lehX1AWXpQaKN0j+oy1RSwLIUYdAXlA4K4TEd//Y9Sl12uXPxCee293l+Y0WE5lCWCiKRb0vxnqXU6gqoRKFcGjHUl2ufjAlDi+WD2yl/8XU0dRSrdRN/qtyyn6reSG/38a/40+rXN3HQ56kR/hLQD4DUMdn4hvaubHu9nWjSGjpVhMahG6c2/7cNyOX1tqsytPLyIuBG88uWjgJZ75OjY3muhgV3cP7EQxp7LnBB9a26+jCpS7eflGM+fyFQIyTVKrWWVtWvJrETFqZoNHRInYf/ZKjBZ/ScRqaNTFUYwRsjzdCeV7nGC5oUvwuikxxG/Ng9oL3MySETt8Bxcnd8mzRT4ve+Aka8pheoYUhrUtUdrQzkAczNc9a4AnyKrYk2n+UaTFm41puhLdBADVlOHRMAJCjGcf0cyf7w66JnquJ46dTHJwh9McdaV8BCigwCraL59slwSuvLIU5FsU10npo13be7GnG/SWd2L+x28efQvay4KJuKK+KfVPxH8fWvGdrZ9h7RdMXwAlcUdRp+aOr77oLeRKOyt2gzur+mBP3WWeRHlQp9Y8i41QhVI9aLR2/lwsUXYPoe5NmCtmIb91ER7bI=
  file:
  - busybox-win32.exe
  - busybox-win64.exe
  - MD5SUMS
  - SHA1SUMS
  - SHA256SUMS
  - SHA512SUMS
  on:
    repo: takumin/test-busybox-windows
    tags: true
    all_branches: true
  skip_cleanup: true
